; Atom CP/M 2.2 transient adapter.
;
; The generated COM links the native Atom core at $0110. The first sixteen
; bytes are supplied by scripts/generate-cpm22.mjs. Source is loaded through
; BDOS into one bounded part; output is patched in TPA and published through a
; temporary file only after Atom commits.

CP_BDOS             EQU $0005
CP_SOURCE_START     EQU $4000
CP_SOURCE_END       EQU $5000
CP_SYMBOL_START     EQU $5000
CP_SYMBOL_END       EQU $8000
CP_PENDING_START    EQU $8000
CP_PENDING_END      EQU $9000
CP_OUTPUT_START     EQU $9000
CP_OUTPUT_END       EQU $D780
CP_SOURCE_PROBE     EQU $D780
CP_SOURCE_PROBE_END EQU $D800
CP_TARGET_START     EQU $0100
CP_TARGET_CAPACITY  EQU $4780
CP_STACK_TOP        EQU $E400
CP_DMA_FUNCTION     EQU 26
CP_OPEN_FUNCTION    EQU 15
CP_CLOSE_FUNCTION   EQU 16
CP_DELETE_FUNCTION  EQU 19
CP_READ_FUNCTION    EQU 20
CP_WRITE_FUNCTION   EQU 21
CP_MAKE_FUNCTION    EQU 22
CP_RENAME_FUNCTION  EQU 23
CP_PRINT_FUNCTION   EQU 9

CP_ADAPTER_CODE_START:
;@ROUTINE CLOBBERS A,BC,DE,HL,IX,IY,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_ENTRY:
LD   (CP_SAVED_SP),SP
LD   SP,CP_STACK_TOP
CALL CP_LOAD_SOURCE
JR   C,CP_SOURCE_FAILED
LD   HL,CP_OUTPUT_START
LD   DE,CP_OUTPUT_START+1
LD   BC,CP_OUTPUT_END-CP_OUTPUT_START-1
LD   (HL),0
LDIR
LD   IX,CP_DESCRIPTOR
CALL DR_ASM
JR   C,CP_ASSEMBLY_FAILED
LD   DE,CP_SUCCESS_TEXT
CALL CP_PRINT
JR   CP_RETURN
CP_SOURCE_FAILED:
LD   DE,CP_SOURCE_TEXT
CALL CP_PRINT
JR   CP_RETURN
CP_ASSEMBLY_FAILED:
PUSH AF
LD   DE,CP_ASSEMBLY_TEXT
CALL CP_PRINT
POP  AF
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   A,(ST_EPART)
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   HL,(ST_EOFF)
PUSH HL
LD   A,H
CALL CP_PRINT_HEX
POP  HL
LD   A,L
CALL CP_PRINT_HEX
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
CP_RETURN:
LD   SP,(CP_SAVED_SP)
RET

; Load INPUT.ASM as one logical source part. CP/M text EOF ($1A) terminates the
; logical bytes; an exact-record file may instead end at BDOS EOF.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_LOAD_SOURCE:
LD   DE,CP_INPUT_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_IO_FAILURE
LD   HL,CP_SOURCE_START
CP_SOURCE_RECORD:
PUSH HL
LD   DE,CP_SOURCE_END-128
OR   A
SBC  HL,DE
POP  HL
JR   C,CP_SOURCE_READ
JR   Z,CP_SOURCE_READ
LD   DE,CP_SOURCE_END
OR   A
SBC  HL,DE
JR   NZ,CP_IO_FAILURE
LD   DE,CP_SOURCE_PROBE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_INPUT_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
CP   1
JR   NZ,CP_IO_FAILURE
LD   HL,CP_SOURCE_END
JR   CP_SOURCE_DONE
CP_SOURCE_READ:
PUSH HL
EX   DE,HL
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_INPUT_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
POP  HL
OR   A
JR   Z,CP_SOURCE_SCAN
CP   1
JR   NZ,CP_IO_FAILURE
JR   CP_SOURCE_DONE
CP_SOURCE_SCAN:
LD   B,128
CP_SOURCE_SCAN_BYTE:
LD   A,(HL)
CP   $1A
JR   Z,CP_SOURCE_DONE
INC  HL
DJNZ CP_SOURCE_SCAN_BYTE
JR   CP_SOURCE_RECORD
CP_SOURCE_DONE:
LD   (CP_PART_END),HL
LD   DE,CP_INPUT_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_IO_FAILURE
XOR  A
RET
CP_IO_FAILURE:
LD   A,1
SCF
RET

; Nucleus-model sink entries linked directly in place of the host stubs.
CP_OUTPUT_CODE_START:
HS_SCBEG:
;@ROUTINE IN IX OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
HS_BEG:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_IB:
HS_PB:
PUSH AF
LD   DE,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,DE
POP  AF
LD   (HL),A
XOR  A
RET

;@ROUTINE IN C,DE,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_PW:
EX   DE,HL
LD   BC,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,BC
LD   (HL),E
INC  HL
LD   (HL),D
XOR  A
RET

;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_CMT:
LD   DE,CP_TARGET_START
OR   A
SBC  HL,DE
LD   (CP_OUTPUT_REMAINING),HL
LD   HL,CP_OUTPUT_START
LD   (CP_OUTPUT_CURSOR),HL
LD   DE,CP_TEMP_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   DE,CP_TEMP_FCB
LD   C,CP_MAKE_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_COMMIT_FAILURE
LD   A,1
LD   (CP_OUTPUT_OPEN),A
CP_WRITE_LOOP:
LD   HL,(CP_OUTPUT_REMAINING)
LD   A,H
OR   L
JR   Z,CP_WRITE_CLOSE
LD   DE,(CP_OUTPUT_CURSOR)
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_TEMP_FCB
LD   C,CP_WRITE_FUNCTION
CALL CP_BDOS
OR   A
JR   NZ,CP_COMMIT_FAILURE
LD   HL,(CP_OUTPUT_CURSOR)
LD   DE,128
ADD  HL,DE
LD   (CP_OUTPUT_CURSOR),HL
LD   HL,(CP_OUTPUT_REMAINING)
LD   DE,128
OR   A
SBC  HL,DE
JR   NC,CP_WRITE_MORE
LD   HL,0
CP_WRITE_MORE:
LD   (CP_OUTPUT_REMAINING),HL
JR   CP_WRITE_LOOP
CP_WRITE_CLOSE:
LD   DE,CP_TEMP_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_COMMIT_FAILURE
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   DE,CP_BACKUP_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   DE,CP_OUTPUT_TO_BACKUP_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_NO_BACKUP
LD   A,1
LD   (CP_BACKED_UP),A
CP_NO_BACKUP:
LD   DE,CP_TEMP_TO_OUTPUT_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_COMMIT_FAILURE
LD   DE,CP_BACKUP_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
XOR  A
LD   (CP_BACKED_UP),A
RET
CP_COMMIT_FAILURE:
LD   A,1
SCF
RET

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_ABORT:
LD   A,(CP_OUTPUT_OPEN)
OR   A
JR   Z,CP_ABORT_DELETE
LD   DE,CP_TEMP_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
CP_ABORT_DELETE:
LD   DE,CP_TEMP_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   A,(CP_BACKED_UP)
OR   A
JR   Z,CP_ABORT_DONE
LD   DE,CP_BACKUP_TO_OUTPUT_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
CP_ABORT_DONE:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

CP_OUTPUT_CODE_END:
;@ROUTINE IN DE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT:
LD   C,CP_PRINT_FUNCTION
JP   CP_BDOS
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PUTC:
PUSH DE
LD   E,A
LD   C,2
CALL CP_BDOS
POP  DE
RET
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_HEX:
PUSH AF
RRCA
RRCA
RRCA
RRCA
CALL CP_PRINT_NIBBLE
POP  AF
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NIBBLE:
AND  $0F
ADD  A,'0'
CP   '9'+1
JR   C,CP_PUTC
ADD  A,7
JR   CP_PUTC

CP_ADAPTER_CODE_END:
CP_ADAPTER_WORKSPACE1_START:
CP_DESCRIPTOR:
DB   1
DW   CP_PART_DESCRIPTOR
DW   CP_SYMBOL_START,CP_SYMBOL_END
DW   CP_PENDING_START,CP_PENDING_END
DW   CP_TARGET_START,CP_TARGET_CAPACITY
CP_PART_DESCRIPTOR:
DB   0
DW   CP_SOURCE_START
CP_PART_END: DW CP_SOURCE_START

CP_INPUT_FCB:
DB 0,'I','N','P','U','T',' ',' ',' ','A','S','M'
DS 24
CP_TEMP_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','$','$','$'
DS 24
CP_BACKUP_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','B','A','K'
DS 24
CP_OUTPUT_TO_BACKUP_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
DS 4
DB 0,'O','U','T','P','U','T',' ',' ','B','A','K'
DS 8
CP_TEMP_TO_OUTPUT_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','$','$','$'
DS 4
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
DS 8
CP_BACKUP_TO_OUTPUT_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','B','A','K'
DS 4
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
DS 8
CP_ADAPTER_WORKSPACE1_END:

CP_ADAPTER_IMMUTABLE_START:
CP_SUCCESS_TEXT: DB 13,10,'O','U','T','P','U','T','.','C','O','M',' ','w','r','i','t','t','e','n',13,10,'$'
CP_SOURCE_TEXT: DB 13,10,'I','N','P','U','T','.','A','S','M',' ','r','e','a','d',' ','f','a','i','l','e','d',13,10,'$'
CP_ASSEMBLY_TEXT: DB 13,10,'A','t','o','m',' ','e','r','r','o','r',' ','$'
CP_NEWLINE_TEXT: DB 13,10,'$'
CP_ADAPTER_IMMUTABLE_END:
CP_ADAPTER_WORKSPACE2_START:
CP_SAVED_SP: DW 0
CP_OUTPUT_CURSOR: DW 0
CP_OUTPUT_REMAINING: DW 0
CP_OUTPUT_OPEN: DB 0
CP_BACKED_UP: DB 0
CP_ADAPTER_WORKSPACE2_END:
HS_SCEND:
HS_REND:
CP_RESIDENT_END:
