; Atom CP/M 2.2 transient adapter.
;
; The generated COM links the native Atom core at $0110. The first sixteen
; bytes are supplied by scripts/generate-cpm22.mjs. Source is loaded through
; BDOS into one bounded part; output is patched in TPA and published through a
; temporary file only after Atom commits.

CP_BDOS             EQU $0005
CP_SOURCE_START     EQU $4000
CP_SOURCE_END       EQU $5000
CP_SYMBOL_START     EQU $5000
CP_SYMBOL_END       EQU $8000
CP_PENDING_START    EQU $8000
CP_PENDING_END      EQU $9000
CP_OUTPUT_START     EQU $9000
CP_OUTPUT_END       EQU $D780
CP_SOURCE_PROBE     EQU $D780
CP_SOURCE_PROBE_END EQU $D800
CP_TARGET_START     EQU $0100
CP_TARGET_CAPACITY  EQU $4780
CP_STACK_TOP        EQU $E400
CP_DMA_FUNCTION     EQU 26
CP_OPEN_FUNCTION    EQU 15
CP_CLOSE_FUNCTION   EQU 16
CP_DELETE_FUNCTION  EQU 19
CP_READ_FUNCTION    EQU 20
CP_WRITE_FUNCTION   EQU 21
CP_MAKE_FUNCTION    EQU 22
CP_RENAME_FUNCTION  EQU 23
CP_PRINT_FUNCTION   EQU 9
CP_COMMAND_LENGTH   EQU $0080
CP_COMMAND_START    EQU $0081

CP_ADAPTER_CODE_START:
;@ROUTINE CLOBBERS A,BC,DE,HL,IX,IY,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_ENTRY:
LD   (CP_SAVED_SP),SP
LD   SP,CP_STACK_TOP
CALL CP_PARSE_COMMAND
JR   C,CP_COMMAND_FAILED
CALL CP_LOAD_SOURCE
JR   C,CP_SOURCE_FAILED
LD   HL,CP_OUTPUT_START
LD   DE,CP_OUTPUT_START+1
LD   BC,CP_OUTPUT_END-CP_OUTPUT_START-1
LD   (HL),0
LDIR
LD   IX,CP_DESCRIPTOR
CALL DR_ASM
JR   C,CP_ASSEMBLY_FAILED
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
LD   HL,CP_OUTPUT_NAME
CALL CP_PRINT_NAME
LD   DE,CP_WRITTEN_TEXT
CALL CP_PRINT
JR   CP_RETURN
CP_SOURCE_FAILED:
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
LD   HL,CP_INPUT_FCB
CALL CP_PRINT_NAME
LD   DE,CP_READ_FAILED_TEXT
CALL CP_PRINT
JR   CP_RETURN
CP_COMMAND_FAILED:
CALL CP_PRINT
JR   CP_RETURN
CP_ASSEMBLY_FAILED:
PUSH AF
LD   DE,CP_ASSEMBLY_TEXT
CALL CP_PRINT
POP  AF
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   A,(ST_EPART)
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   HL,(ST_EOFF)
PUSH HL
LD   A,H
CALL CP_PRINT_HEX
POP  HL
LD   A,L
CALL CP_PRINT_HEX
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
CP_RETURN:
LD   SP,(CP_SAVED_SP)
RET

CP_COMMAND_CODE_START:
; Accept either no arguments or exactly two current-drive CP/M 8.3 names.
; The CCP has already canonicalised those names into its two default FCBs.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_COMMAND:
LD   A,(CP_COMMAND_LENGTH)
LD   B,A
LD   HL,CP_COMMAND_START
CALL CP_SKIP_SPACES
JP   Z,CP_CHECK_AUXILIARY_NAMES
CALL CP_PARSE_FILENAME
JR   C,CP_BAD_SOURCE_NAME
CALL CP_SKIP_SPACES
JR   Z,CP_BAD_USAGE
CALL CP_PARSE_FILENAME
JR   C,CP_BAD_OUTPUT_NAME
CALL CP_SKIP_SPACES
JR   NZ,CP_BAD_USAGE
LD   HL,$005C
LD   DE,CP_INPUT_FCB
LD   BC,12
LDIR
LD   HL,$006C
LD   DE,CP_OUTPUT_NAME
LD   BC,12
LDIR
LD   HL,CP_OUTPUT_NAME+9
LD   DE,CP_COM_EXTENSION
LD   B,3
CP_OUTPUT_TYPE_BYTE:
LD   A,(DE)
CP   (HL)
JR   NZ,CP_BAD_OUTPUT_NAME
INC  DE
INC  HL
DJNZ CP_OUTPUT_TYPE_BYTE
LD   HL,CP_INPUT_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
CALL CP_SET_TEMP_FCB
CALL CP_CHECK_WORK_NAME
RET  C
CALL CP_SET_BACKUP_FCB
CALL CP_CHECK_WORK_NAME
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_WORK_NAME:
LD   HL,CP_INPUT_FCB
LD   DE,CP_WORK_FCB
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
JP   CP_AUXILIARY_MUST_NOT_EXIST
CP_BAD_USAGE:
LD   DE,CP_USAGE_TEXT
SCF
RET
CP_BAD_SOURCE_NAME:
LD   DE,CP_SOURCE_NAME_TEXT
SCF
RET
CP_BAD_OUTPUT_NAME:
LD   DE,CP_OUTPUT_NAME_TEXT
SCF
RET
CP_BAD_NAME_CONFLICT:
LD   DE,CP_NAME_CONFLICT_TEXT
SCF
RET

; Refuse to claim pre-existing temporary or backup files. CP/M is
; single-tasking, so successful preflight reserves both names until return.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_AUXILIARY_NAMES:
CALL CP_SET_TEMP_FCB
CALL CP_AUXILIARY_MUST_NOT_EXIST
RET  C
CALL CP_SET_BACKUP_FCB
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_AUXILIARY_MUST_NOT_EXIST:
LD   DE,CP_WORK_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_AUXILIARY_AVAILABLE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
LD   DE,CP_AUXILIARY_EXISTS_TEXT
SCF
RET
CP_AUXILIARY_AVAILABLE:
XOR  A
RET

;@ROUTINE IN B,HL OUT A,B,HL,ZERO CLOBBERS CARRY,SIGN,PARITY,HALFCARRY
CP_SKIP_SPACES:
LD   A,B
OR   A
RET  Z
LD   A,(HL)
CP   ' '
RET  NZ
INC  HL
DEC  B
JR   CP_SKIP_SPACES

; Parse one unquoted, current-drive 8.3 filename without consuming its
; trailing space. Carry reports an empty, overlong, wildcard, drive-qualified,
; or otherwise invalid field.
;@ROUTINE IN B,HL OUT A,B,HL,CARRY CLOBBERS C,D,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_FILENAME:
LD   D,8
LD   C,0
CP_PARSE_FILENAME_BYTE:
LD   A,B
OR   A
JR   Z,CP_FILENAME_DONE
LD   A,(HL)
CP   ' '
JR   Z,CP_FILENAME_DONE
CP   '.'
JR   NZ,CP_FILENAME_DATA
LD   A,D
CP   8
JR   NZ,CP_FILENAME_FAILURE
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
LD   D,3
LD   C,0
JR   CP_FILENAME_CONSUME
CP_FILENAME_DATA:
CALL CP_FILENAME_CHAR
RET  C
INC  C
LD   A,D
CP   C
JR   C,CP_FILENAME_FAILURE
CP_FILENAME_CONSUME:
INC  HL
DEC  B
JR   CP_PARSE_FILENAME_BYTE
CP_FILENAME_DONE:
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
RET
CP_FILENAME_FAILURE:
SCF
RET

;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_FILENAME_CHAR:
CP   '!'
RET  C
CP   $7F
JR   NC,CP_FILENAME_CHAR_BAD
CP   '*'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '-'
JR   C,CP_FILENAME_CHAR_BAD
CP   '/'
JR   Z,CP_FILENAME_CHAR_BAD
CP   ':'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '@'
JR   C,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_HIGH:
CP   '['
JR   C,CP_FILENAME_CHAR_OK
CP   '^'
JR   C,CP_FILENAME_CHAR_BAD
CP   '_'
JR   Z,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_OK:
OR   A
RET
CP_FILENAME_CHAR_BAD:
SCF
RET

;@ROUTINE IN DE,HL OUT A,ZERO CLOBBERS B,DE,HL,CARRY,SIGN,PARITY,HALFCARRY
CP_NAMES_EQUAL:
LD   B,12
CP_NAMES_EQUAL_BYTE:
LD   A,(DE)
CP   (HL)
RET  NZ
INC  DE
INC  HL
DJNZ CP_NAMES_EQUAL_BYTE
XOR  A
RET
CP_COMMAND_CODE_END:

; Load the selected input as one logical source part. CP/M text EOF ($1A) terminates the
; logical bytes; an exact-record file may instead end at BDOS EOF.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_LOAD_SOURCE:
LD   DE,CP_INPUT_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_IO_FAILURE
LD   HL,CP_SOURCE_START
CP_SOURCE_RECORD:
PUSH HL
LD   DE,CP_SOURCE_END-128
OR   A
SBC  HL,DE
POP  HL
JR   C,CP_SOURCE_READ
JR   Z,CP_SOURCE_READ
LD   DE,CP_SOURCE_END
OR   A
SBC  HL,DE
JR   NZ,CP_IO_FAILURE
LD   DE,CP_SOURCE_PROBE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_INPUT_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
CP   1
JR   NZ,CP_IO_FAILURE
LD   HL,CP_SOURCE_END
JR   CP_SOURCE_DONE
CP_SOURCE_READ:
PUSH HL
EX   DE,HL
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_INPUT_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
POP  HL
OR   A
JR   Z,CP_SOURCE_SCAN
CP   1
JR   NZ,CP_IO_FAILURE
JR   CP_SOURCE_DONE
CP_SOURCE_SCAN:
LD   B,128
CP_SOURCE_SCAN_BYTE:
LD   A,(HL)
CP   $1A
JR   Z,CP_SOURCE_DONE
INC  HL
DJNZ CP_SOURCE_SCAN_BYTE
JR   CP_SOURCE_RECORD
CP_SOURCE_DONE:
LD   (CP_PART_END),HL
LD   DE,CP_INPUT_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_IO_FAILURE
XOR  A
RET
CP_IO_FAILURE:
LD   A,1
SCF
RET

; Nucleus-model sink entries linked directly in place of the host stubs.
CP_OUTPUT_CODE_START:
HS_SCBEG:
;@ROUTINE IN IX OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
HS_BEG:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_IB:
HS_PB:
PUSH AF
LD   DE,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,DE
POP  AF
LD   (HL),A
XOR  A
RET

;@ROUTINE IN C,DE,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_PW:
EX   DE,HL
LD   BC,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,BC
LD   (HL),E
INC  HL
LD   (HL),D
XOR  A
RET

;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_CMT:
LD   DE,CP_TARGET_START
OR   A
SBC  HL,DE
LD   (CP_OUTPUT_REMAINING),HL
LD   HL,CP_OUTPUT_START
LD   (CP_OUTPUT_CURSOR),HL
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_MAKE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
LD   A,1
LD   (CP_OUTPUT_OPEN),A
CP_WRITE_LOOP:
LD   HL,(CP_OUTPUT_REMAINING)
LD   A,H
OR   L
JR   Z,CP_WRITE_CLOSE
LD   DE,(CP_OUTPUT_CURSOR)
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_WORK_FCB
LD   C,CP_WRITE_FUNCTION
CALL CP_BDOS
OR   A
JP   NZ,CP_COMMIT_FAILURE
LD   HL,(CP_OUTPUT_CURSOR)
LD   DE,128
ADD  HL,DE
LD   (CP_OUTPUT_CURSOR),HL
LD   HL,(CP_OUTPUT_REMAINING)
LD   DE,128
OR   A
SBC  HL,DE
JR   NC,CP_WRITE_MORE
LD   HL,0
CP_WRITE_MORE:
LD   (CP_OUTPUT_REMAINING),HL
JR   CP_WRITE_LOOP
CP_WRITE_CLOSE:
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
XOR  A
LD   (CP_OUTPUT_OPEN),A
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_NO_BACKUP
LD   A,1
LD   (CP_BACKED_UP),A
CP_NO_BACKUP:
CALL CP_SET_TEMP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
XOR  A
LD   (CP_BACKED_UP),A
RET
CP_COMMIT_FAILURE:
LD   A,1
SCF
RET

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_ABORT:
LD   A,(CP_OUTPUT_OPEN)
OR   A
JR   Z,CP_ABORT_DELETE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
CP_ABORT_DELETE:
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   A,(CP_BACKED_UP)
OR   A
JR   Z,CP_ABORT_DONE
CALL CP_SET_BACKUP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
CP_ABORT_DONE:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

; Rebuild the single ordinary output FCB before each new BDOS operation phase.
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_COPY_OUTPUT_FCB:
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
LD   BC,12
LDIR
XOR  A
LD   B,24
CP_CLEAR_WORK_FCB:
LD   (DE),A
INC  DE
DJNZ CP_CLEAR_WORK_FCB
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_TEMP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$2424
LD   (CP_WORK_FCB+9),HL
LD   A,'$'
LD   (CP_WORK_FCB+11),A
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_BACKUP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$4142
LD   (CP_WORK_FCB+9),HL
LD   A,'K'
LD   (CP_WORK_FCB+11),A
RET

; Construct a CP/M rename FCB in the input FCB's dead storage. HL addresses
; the old 12-byte name and DE the new 12-byte name.
;@ROUTINE IN DE,HL CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_BUILD_RENAME:
PUSH HL
PUSH DE
LD   HL,CP_RENAME_FCB
LD   DE,CP_RENAME_FCB+1
LD   BC,35
LD   (HL),0
LDIR
POP  DE
POP  HL
PUSH DE
LD   DE,CP_RENAME_FCB
LD   BC,12
LDIR
POP  HL
LD   DE,CP_RENAME_FCB+16
LD   BC,12
LDIR
RET

CP_OUTPUT_CODE_END:
;@ROUTINE IN DE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT:
LD   C,CP_PRINT_FUNCTION
JP   CP_BDOS
;@ROUTINE IN HL OUT A CLOBBERS B,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NAME:
INC  HL
LD   B,8
CP_PRINT_NAME_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_NAME_BYTE
LD   A,(HL)
CP   ' '
RET  Z
LD   A,'.'
CALL CP_PUTC
LD   B,3
CP_PRINT_TYPE_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_TYPE_BYTE
RET
;@ROUTINE IN A OUT A CLOBBERS CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PUTC:
PUSH BC
PUSH DE
PUSH HL
LD   E,A
LD   C,2
CALL CP_BDOS
POP  HL
POP  DE
POP  BC
RET
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_HEX:
PUSH AF
RRCA
RRCA
RRCA
RRCA
CALL CP_PRINT_NIBBLE
POP  AF
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NIBBLE:
AND  $0F
ADD  A,'0'
CP   '9'+1
JR   C,CP_PUTC
ADD  A,7
JR   CP_PUTC

CP_ADAPTER_CODE_END:
CP_ADAPTER_WORKSPACE1_START:
CP_DESCRIPTOR:
DB   1
DW   CP_PART_DESCRIPTOR
DW   CP_SYMBOL_START,CP_SYMBOL_END
DW   CP_PENDING_START,CP_PENDING_END
DW   CP_TARGET_START,CP_TARGET_CAPACITY
CP_PART_DESCRIPTOR:
DB   0
DW   CP_SOURCE_START
CP_PART_END: DW CP_SOURCE_START

CP_RENAME_FCB:
CP_INPUT_FCB:
DB 0,'I','N','P','U','T',' ',' ',' ','A','S','M'
DS 24
CP_WORK_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','$','$','$'
DS 24
CP_OUTPUT_NAME:
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
CP_ADAPTER_WORKSPACE1_END:

CP_ADAPTER_IMMUTABLE_START:
CP_WRITTEN_TEXT: DB ' ','w','r','i','t','t','e','n',13,10,'$'
CP_READ_FAILED_TEXT: DB ' ','r','e','a','d',' ','f','a','i','l','e','d',13,10,'$'
CP_ASSEMBLY_TEXT: DB 13,10,'A','t','o','m',' ','e','r','r','o','r',' ','$'
CP_NEWLINE_TEXT: DB 13,10,'$'
CP_USAGE_TEXT: DB 13,10,'U','s','a','g','e',':',' ','A','T','O','M',' ','[','S','O','U','R','C','E',' ','O','U','T','P','U','T','.','C','O','M',']',13,10,'$'
CP_SOURCE_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','s','o','u','r','c','e',' ','n','a','m','e',13,10,'$'
CP_OUTPUT_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','o','u','t','p','u','t',' ','n','a','m','e',13,10,'$'
CP_NAME_CONFLICT_TEXT: DB 13,10,'S','o','u','r','c','e','/','o','u','t','p','u','t',' ','c','o','n','f','l','i','c','t',13,10,'$'
CP_AUXILIARY_EXISTS_TEXT: DB 13,10,'T','e','m','p','/','b','a','c','k','u','p',' ','f','i','l','e',' ','e','x','i','s','t','s',13,10,'$'
CP_COM_EXTENSION: DB 'C','O','M'
CP_ADAPTER_IMMUTABLE_END:
CP_ADAPTER_WORKSPACE2_START:
CP_SAVED_SP: DW 0
CP_OUTPUT_CURSOR: DW 0
CP_OUTPUT_REMAINING: DW 0
CP_OUTPUT_OPEN: DB 0
CP_BACKED_UP: DB 0
CP_ADAPTER_WORKSPACE2_END:
HS_SCEND:
HS_REND:
CP_RESIDENT_END:
