;==============================================================================
;  Logical output and patch submission
;==============================================================================
;
;  Maintain the logical target cursor and remaining capacity. IMAGE operations
;  append bytes as statements are assembled. Defining a referenced symbol
;  calculates its final field value and submits PATCH operations before the
;  corresponding pending records are removed.
;
;  Principal entries:
;    OU_RESET  initialise logical output state
;    OU_EMITB  emit one IMAGE byte
;    OU_EMITW  emit one little-endian IMAGE word
;    OU_RESER  reserve a target interval
;    OU_SORIG  change the logical origin
;    OU_EINS   encode and emit one parsed instruction
;    OU_RSLV   resolve and submit every pending patch for a symbol
;
;  Sink failure never removes a pending record or advances state that has not
;  been accepted by the platform.

OU_CBEG:
OU_SCAP EQU 1
OU_SINT EQU 2
OU_SVRAN EQU 3
OU_SRRAN EQU 4
;@ROUTINE IN DE,HL OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
OU_RESET:
LD   (OU_CURSO),HL
LD   (OU_REM),DE
XOR  A
RET
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,SIGN,PARITY,HALFCARRY,HL,ZERO
OU_CCAP:
EX   DE,HL
LD   HL,(OU_REM)
OR   A
SBC  HL,DE
JR   C,OU_DCFAI
XOR  A
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
OU_EMITB:
LD   B,A
LD   HL,1
CALL OU_CCAP
RET  C
LD   A,B
JR   OU_EBREA
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
OU_EMITW:
LD   B,H
LD   C,L
LD   HL,2
CALL OU_CCAP
RET  C
LD   A,C
PUSH BC
CALL OU_EBREA
POP  BC
RET  C
LD   A,B
JR   OU_EBREA
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
OU_RESER:
PUSH HL
CALL OU_CCAP
POP  DE
RET  C
LD   HL,(OU_CURSO)
ADD  HL,DE
LD   (OU_CURSO),HL
LD   HL,(OU_REM)
OR   A
SBC  HL,DE
LD   (OU_REM),HL
XOR  A
RET
;@ROUTINE IN HL OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
OU_SORIG:
LD   (OU_CURSO),HL
XOR  A
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS BC,HL,ZERO,SIGN,PARITY,HALFCARRY,DE,IX,IY
OU_EBREA:
LD   HL,(OU_CURSO)
LD   C,0
CALL HS_IB
RET  C
LD   HL,(OU_CURSO)
INC  HL
LD   (OU_CURSO),HL
LD   HL,(OU_REM)
DEC  HL
LD   (OU_REM),HL
XOR  A
RET
OU_DCFAI:
LD   A,OU_SCAP
SCF
RET
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IX,IY
OU_EINS:
LD   HL,(OU_CURSO)
LD   (OU_IBEG),HL
LD   DE,OU_INSB
CALL EN_NAME
RET  C
LD   (OU_ILEN),A
LD   B,A
LD   HL,(OU_REM)
LD   A,H
OR   A
JR   NZ,.ICREADY
LD   A,L
CP   B
JR   C,.ICFAIL
.ICREADY:
CALL PR_CREFE
RET  C
XOR  A
LD   (OU_ISCAN),A
.INSLOOP:
LD   A,(OU_ILEN)
LD   B,A
LD   A,(OU_ISCAN)
CP   B
JR   Z,.INSDONE
LD   E,A
LD   D,0
LD   HL,OU_INSB
ADD  HL,DE
LD   A,(HL)
CALL OU_EBREA
RET  C
LD   HL,OU_ISCAN
INC  (HL)
JR   .INSLOOP
.INSDONE:
LD   DE,(OU_IBEG)
JP   PR_QREFE
.ICFAIL:
LD   A,OU_SCAP
SCF
RET
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
OU_RSLV:
BIT  6,(IX+5)
JP   Z,OU_RINT
PUSH IX
POP  HL
LD   (OU_RSPTR),HL
.RSLVLOOP:
LD   IX,(OU_RSPTR)
;@EXPECTOUT A,CARRY,BC,DE
CALL SY_PEEK
JP   C,.RPFAIL
LD   (OU_RPADR),DE
LD   A,B
AND  SY_KMASK
LD   (OU_RKIND),A
LD   A,C
LD   (OU_RADDE),A
LD   IX,(OU_RSPTR)
LD   L,(IX+SY_VALLO)
LD   H,(IX+SY_VALHI)
XOR  A
BIT  5,(IX+5)
JR   Z,.RBREADY
DEC  A
.RBREADY:
LD   (OU_RBHI),A
LD   A,(OU_RADDE)
LD   C,A
LD   D,0
BIT  7,C
JR   Z,.RSREADY
DEC  D
.RSREADY:
LD   A,L
ADD  A,C
LD   (OU_RVAL),A
LD   A,H
ADC  A,D
LD   (OU_RVAL+1),A
LD   A,(OU_RBHI)
ADC  A,D
LD   (OU_RVAL+2),A
CALL OU_RWDOM
RET  C
LD   A,(OU_RKIND)
CP   PT_KINDB
JR   Z,.RSLVB
CP   PT_KINDW
JR   Z,.RSLVW
CP   PT_KRELA
JR   Z,.RRELATIV
CP   PT_KDISP
JR   Z,.RDISPLAC
CP   PT_KTB
JR   Z,.RSB
CP   PT_KLB
JR   Z,.RSB
CP   PT_KHB
JP   NZ,OU_RINT
.RSLVHIB:
LD   A,(OU_RVAL+1)
JR   .RSBA
.RSLVB:
LD   A,(OU_RVAL+2)
OR   A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
OR   A
JR   NZ,OU_RVRAN
JR   .RSB
.RDISPLAC:
LD   A,(OU_RVAL+2)
OR   A
JR   Z,.RDPOSITI
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL)
BIT  7,A
JR   Z,OU_RVRAN
JR   .RSB
.RDPOSITI:
LD   A,(OU_RVAL+1)
OR   A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL)
BIT  7,A
JR   NZ,OU_RVRAN
JR   .RSB
.RRELATIV:
LD   HL,(OU_RVAL)
LD   DE,(OU_RPADR)
INC  DE
OR   A
SBC  HL,DE
LD   A,H
OR   A
JR   Z,.RRPOSITI
INC  A
JR   NZ,OU_RRRAN
BIT  7,L
JR   Z,OU_RRRAN
LD   A,L
JR   .RSBA
.RRPOSITI:
BIT  7,L
JR   NZ,OU_RRRAN
LD   A,L
JR   .RSBA
.RSB:
LD   A,(OU_RVAL)
.RSBA:
LD   HL,(OU_RPADR)
LD   C,0
CALL HS_PB
RET  C
JR   .RREMOVE
.RSLVW:
LD   HL,(OU_RVAL)
LD   DE,(OU_RPADR)
LD   C,0
CALL HS_PW
RET  C
.RREMOVE:
LD   IX,(OU_RSPTR)
;@EXPECTOUT A,CARRY,BC,DE
CALL SY_TAKE
JR   C,OU_RINT
JP   .RSLVLOOP
.RPFAIL:
CP   SY_SNFOU
RET  NZ
XOR  A
RET
OU_RVRAN:
LD   A,OU_SVRAN
SCF
RET
OU_RRRAN:
LD   A,OU_SRRAN
SCF
RET
OU_RINT:
LD   A,OU_SINT
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,BC,DE,HL,IX,IY
OU_RWDOM:
LD   A,(OU_RVAL+2)
OR   A
RET  Z
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
BIT  7,A
RET  NZ
JR   OU_RVRAN
OU_CEND:
OU_WBEG:
OU_CURSO: DW 0
OU_REM: DW 0
OU_WUNIO: DS 10
OU_IBEG EQU OU_WUNIO
OU_INSB EQU OU_WUNIO+2
OU_ILEN EQU OU_WUNIO+6
OU_ISCAN EQU OU_WUNIO+7
OU_RSPTR EQU OU_WUNIO
OU_RPADR EQU OU_WUNIO+2
OU_RKIND EQU OU_WUNIO+4
OU_RADDE EQU OU_WUNIO+5
OU_RVAL EQU OU_WUNIO+6
OU_RBHI EQU OU_WUNIO+9
OU_WEND:
