;==============================================================================
;  Statements, labels and directives
;==============================================================================
;
;  Consume complete source statements. The first name selects a label, equate,
;  directive or instruction path. Directive handlers implement ORG, DB, DW, DS,
;  ALIGN and the three stored-string forms. Label definitions immediately ask
;  the output module to resolve any waiting patches.
;
;  Principal entries:
;    DR_APART  assemble statements until the current source part ends
;    ST_NEXT   assemble one non-empty statement
;
;  Diagnostic position is captured before nested parsing begins. Every failure
;  path retains the outer statement category, nested status and original source
;  position for the driver.

ST_CBEG:
ST_SOK EQU 0
ST_SLEXI EQU 1
ST_SEXP EQU 2
ST_SDIR EQU 3
ST_SEQUA EQU 4
ST_SSYM EQU 5
ST_SINS EQU 6
ST_SOUT EQU 7
ST_SUNDE EQU 8
ST_SINT EQU 9
ST_EQU EQU 1
ST_ORG EQU 2
ST_DB EQU 3
ST_DW EQU 4
ST_DS EQU 5
ST_CSTR EQU 6
ST_PSTR EQU 7
ST_ISTR EQU 8
ST_ALIGN EQU 9
ST_CNT EQU 9
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
DR_APART:
ST_NEXT:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOF
JP   Z,ST_SUCCE
CP   TK_EOL
JR   Z,ST_NEXT
CP   TK_NAME
JP   NZ,ST_EHERE
CALL ST_CPOSI
CALL TK_LLEXE
LD   DE,ST_KEY
CALL EN_PSYM
JP   C,ST_SFAIL
CALL TK_LLEXE
CALL EN_RECOG
JR   C,ST_NMNEM
LD   (ST_MNEM),A
LD   A,1
LD   (ST_MVALI),A
XOR  A
LD   (ST_DVALI),A
JR   ST_AFNAM
ST_NMNEM:
XOR  A
LD   (ST_MVALI),A
CALL TK_LLEXE
CALL EN_RDIR
JR   C,ST_NDIR
LD   (ST_DIR),A
LD   A,1
LD   (ST_DVALI),A
JR   ST_AFNAM
ST_NDIR:
XOR  A
LD   (ST_DVALI),A
ST_AFNAM:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_COLON
JR   Z,ST_LABEL
LD   A,(ST_MVALI)
OR   A
JP   NZ,ST_IPUB
LD   A,(ST_DVALI)
OR   A
JR   Z,ST_TEQUA
LD   A,(ST_DIR)
JP   ST_DPUB
ST_TEQUA:
LD   A,(TK_REC+TK_KOFF)
CP   TK_NAME
JP   NZ,ST_ESAVE
CALL TK_LLEXE
CALL EN_RDIR
JP   C,ST_ESAVE
CP   ST_EQU
JP   NZ,ST_ESAVE
JP   ST_EQUAT
ST_LABEL:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_NAME
JR   NZ,ST_LPUBL
CALL TK_LLEXE
CALL EN_RDIR
JR   C,ST_LPUBL
CP   ST_EQU
JR   Z,ST_EQUAT
ST_LPUBL:
LD   HL,ST_KEY+5
BIT  7,(HL)
LD   HL,ST_KEY
LD   DE,(OU_CURSO)
JR   NZ,ST_PLABE
CALL SY_DGLAB
JR   ST_LDECL
ST_PLABE:
CALL SY_DECL
ST_LDECL:
JP   C,ST_SFAIL
CALL OU_RSLV
JP   C,ST_OFAIL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_NEXT
CP   TK_NAME
JP   NZ,ST_EHERE
CALL ST_CPOSI
CALL TK_LLEXE
CALL EN_RECOG
JR   C,ST_LDIR
LD   (ST_MNEM),A
CALL TK_NEXT
JP   C,ST_LFAIL
JR   ST_IPUB
ST_LDIR:
CALL TK_LLEXE
CALL EN_RDIR
JP   C,ST_ESAVE
LD   (ST_DIR),A
CALL TK_NEXT
JP   C,ST_LFAIL
LD   A,(ST_DIR)
JR   ST_DPUB
ST_IPUB:
LD   A,(ST_MNEM)
LD   BC,(OU_CURSO)
LD   DE,ST_INS
CALL PR_PUB
JP   C,ST_IFAIL
CALL OU_EINS
ST_OTNEX:
JP   C,ST_OFAIL
JP   ST_NEXT
ST_EQUAT:
CALL TK_NEXT
JP   C,ST_LFAIL
CALL ST_PEXPR
JP   C,ST_EFAIL
OR   A
JP   NZ,ST_EUNRE
LD   (ST_EVAL),HL
XOR  A
LD   HL,EX_RVAL+2
CP   (HL)
JR   Z,ST_ESREA
INC  A
ST_ESREA:
LD   (ST_ESIGN),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_EDELI
LD   HL,ST_KEY
LD   DE,(ST_EVAL)
CALL SY_DECL
JP   C,ST_SFAIL
LD   A,(ST_ESIGN)
OR   A
JR   Z,ST_ERSLV
SET  5,(IX+5)
ST_ERSLV:
CALL OU_RSLV
JR   ST_OTNEX
ST_DPUB:
SUB  ST_ORG
CP   8
JP   NC,ST_ESAVE
ADD  A,A
LD   L,A
LD   H,0
LD   DE,ST_DDTAB
ADD  HL,DE
LD   E,(HL)
INC  HL
LD   D,(HL)
EX   DE,HL
JP   (HL)
ST_DDTAB:
DW ST_ORG1,ST_DB1,ST_DW1,ST_DS1
DW ST_CSTR1,ST_PSTR1,ST_ISTR1
DW ST_ALIG1
ST_ORG1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   (ST_DVAL),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(ST_DVAL)
CALL OU_SORIG
JP   ST_OTNEX
ST_DB1:
LD   A,1
LD   (ST_DWIDT),A
LD   A,PT_KTB
LD   (ST_DPKIN),A
JR   ST_DITEM
ST_DW1:
LD   A,2
LD   (ST_DWIDT),A
LD   A,PT_KINDW
LD   (ST_DPKIN),A
ST_DITEM:
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_DEXP
CP   TK_STRIN
JR   NZ,ST_DEXPR
LD   A,(ST_DWIDT)
CP   1
JP   NZ,ST_DSTR1
XOR  A
LD   (ST_SMODE),A
JP   ST_DSTRI
ST_DEXPR:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JR   NZ,ST_DUNRE
LD   A,(ST_DWIDT)
CP   1
JR   Z,ST_DRB
CALL OU_EMITW
JR   ST_DORES
ST_DRB:
LD   A,L
CALL OU_EMITB
ST_DORES:
JP   C,ST_OFAIL
JP   ST_DDELI
ST_DUNRE:
LD   A,L
LD   (ST_DADDE),A
PUSH IX
POP  HL
LD   (ST_DKEY),HL
LD   A,(ST_DWIDT)
LD   L,A
LD   H,0
CALL OU_CCAP
JP   C,ST_OFAIL
CALL SY_CCAP
JP   C,ST_SFAIL
LD   A,(EX_RUNRE)
CP   EX_FLO
JR   Z,ST_DPLO
CP   EX_FHI
JR   Z,ST_DPHI
LD   A,(ST_DPKIN)
JR   ST_DPKRE
ST_DPLO:
LD   A,PT_KLB
JR   ST_DPKRE
ST_DPHI:
LD   A,PT_KHB
ST_DPKRE:
LD   (ST_DPKI1),A
LD   HL,(ST_DKEY)
CALL SY_REF
JP   C,ST_SFAIL
LD   A,B
OR   A
JR   Z,ST_DDREA
LD   HL,(EX_SOFF)
LD   (IX+SY_VALLO),L
LD   (IX+SY_VALHI),H
LD   A,SY_DANCH
LD   HL,ST_DPKI1
OR   (HL)
LD   (HL),A
ST_DDREA:
PUSH IX
POP  HL
LD   (ST_DSYM),HL
LD   HL,(OU_CURSO)
LD   (ST_DADR),HL
LD   A,(ST_DWIDT)
CP   1
JR   Z,ST_DPB
LD   HL,0
CALL OU_EMITW
JP   C,ST_OFAIL
JR   ST_DQUEU
ST_DPB:
XOR  A
CALL OU_EMITB
JP   C,ST_OFAIL
ST_DQUEU:
LD   IX,(ST_DSYM)
LD   DE,(ST_DADR)
LD   A,(ST_DPKI1)
LD   B,A
LD   A,(ST_DADDE)
LD   C,A
LD   A,(EX_SPART)
CALL SY_ADD
JP   C,ST_SFAIL
ST_DDELI:
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_NEXT
CP   TK_COMMA
JP   NZ,ST_DDEL1
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOL
JP   Z,ST_DEXP
JP   ST_DITEM
ST_DSTRI:
LD   HL,(TK_REC+TK_SOFF)
INC  HL
LD   A,(TK_REC+TK_LOFF1)
SUB  2
LD   B,A
LD   C,0
ST_SCLOO:
LD   A,B
OR   A
JR   Z,ST_SCDON
PUSH HL
LD   A,(TK_REC+TK_POFF)
CALL TK_SREAD
POP  HL
INC  HL
DEC  B
CP   $5C
JR   NZ,ST_SCONE
PUSH HL
LD   A,(TK_REC+TK_POFF)
CALL TK_SREAD
POP  HL
INC  HL
DEC  B
CP   $78
JR   NZ,ST_SCONE
INC  HL
INC  HL
DEC  B
DEC  B
ST_SCONE:
INC  C
JR   ST_SCLOO
ST_SCDON:
LD   A,C
LD   (ST_SCNT),A
LD   HL,(TK_REC+TK_SOFF)
INC  HL
LD   (ST_SPTR),HL
LD   A,(TK_REC+TK_POFF)
LD   (ST_SPART),A
LD   A,(TK_REC+TK_LOFF1)
SUB  2
LD   (ST_SREM),A
LD   A,(ST_SMODE)
OR   A
JR   Z,ST_SCAP
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOL
JP   NZ,ST_DDEL1
ST_SCAP:
LD   A,(ST_SCNT)
LD   L,A
LD   H,0
LD   A,(ST_SMODE)
CP   1
JR   Z,ST_SCEXT
CP   2
JR   NZ,ST_SCREA
ST_SCEXT:
INC  HL
ST_SCREA:
CALL OU_CCAP
JP   C,ST_OFAIL
LD   A,(ST_SMODE)
CP   2
JR   NZ,ST_SELOO
LD   A,(ST_SCNT)
CALL OU_EMITB
JP   C,ST_OFAIL
ST_SELOO:
LD   A,(ST_SREM)
OR   A
JR   Z,ST_SDONE
CALL ST_STAKE
CP   $5C
JR   NZ,ST_SEMIT
CALL ST_STAKE
CP   $78
JR   Z,ST_SHEX
CALL TK_DESCA
JP   C,ST_DSTR1
JR   ST_SEMIT
ST_SHEX:
CALL ST_STAKE
CALL TK_HDIGI
JP   NC,ST_DSTR1
ADD  A,A
ADD  A,A
ADD  A,A
ADD  A,A
LD   (ST_SNIBB),A
CALL ST_STAKE
CALL TK_HDIGI
JP   NC,ST_DSTR1
LD   HL,ST_SNIBB
OR   (HL)
ST_SEMIT:
LD   C,A
LD   A,(ST_SMODE)
CP   3
LD   A,C
JR   NZ,ST_SEREA
LD   HL,ST_SREM
LD   A,(HL)
OR   A
LD   A,C
JR   NZ,ST_SEREA
OR   $80
ST_SEREA:
CALL OU_EMITB
JP   C,ST_OFAIL
JR   ST_SELOO
ST_SDONE:
LD   A,(ST_SMODE)
OR   A
JR   Z,ST_SDDON
CP   1
JP   NZ,ST_NEXT
XOR  A
CALL OU_EMITB
JP   ST_OTNEX
ST_SDDON:
CALL TK_NEXT
JP   C,ST_LFAIL
JP   ST_DDELI
ST_CSTR1:
LD   A,1
JR   ST_SDIR1
ST_PSTR1:
LD   A,2
JR   ST_SDIR1
ST_ISTR1:
LD   A,3
ST_SDIR1:
LD   (ST_SMODE),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_STRIN
JP   NZ,ST_DSTR1
JP   ST_DSTRI
ST_DS1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   (ST_DCNT),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JR   Z,ST_DRESE
CP   TK_COMMA
JP   NZ,ST_DDEL1
CALL TK_NEXT
JP   C,ST_LFAIL
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   A,L
LD   (ST_DFILL),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(ST_DCNT)
CALL OU_CCAP
JP   C,ST_OFAIL
ST_DFLOO:
LD   HL,(ST_DCNT)
LD   A,H
OR   L
JP   Z,ST_NEXT
LD   A,(ST_DFILL)
CALL OU_EMITB
JP   C,ST_OFAIL
LD   HL,(ST_DCNT)
DEC  HL
LD   (ST_DCNT),HL
JR   ST_DFLOO
ST_DRESE:
LD   HL,(ST_DCNT)
CALL OU_RESER
JP   ST_OTNEX
ST_ALIG1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   A,(EX_RVAL+2)
OR   A
JP   NZ,ST_DRANG
LD   A,H
OR   L
JP   Z,ST_DRANG
LD   (ST_DVAL),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(OU_CURSO)
LD   (EX_LVAL),HL
XOR  A
LD   (EX_LVAL+2),A
LD   HL,(ST_DVAL)
LD   (EX_RVAL),HL
LD   (EX_RVAL+2),A
CALL EX_REMAI
JP   C,ST_DFAIL
LD   HL,(EX_RVAL)
LD   A,H
OR   L
JR   Z,ST_ACREA
EX   DE,HL
LD   HL,(ST_DVAL)
OR   A
SBC  HL,DE
ST_ACREA:
LD   (ST_DCNT),HL
XOR  A
LD   (ST_DFILL),A
LD   HL,(ST_DCNT)
CALL OU_CCAP
JP   C,ST_OFAIL
JR   ST_DFLOO
ST_SUCCE:
XOR  A
RET
;@ROUTINE IN B,HL OUT A,CARRY CLOBBERS BC,HL,IX,ZERO,SIGN,PARITY,HALFCARRY,DE
EN_RDIR:
LD   A,B
CP   6
JR   NC,EN_RDNFO
LD   DE,EN_SCRAT
CALL EN_R40PK
RET  C
LD   IX,ST_DTABL
LD   B,ST_CNT
LD   C,ST_EQU
EN_RDLOO:
LD   A,(EN_SCRAT)
CP   (IX+0)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+1)
CP   (IX+1)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+2)
CP   (IX+2)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+3)
CP   (IX+3)
JR   NZ,EN_RDNEX
LD   A,C
OR   A
RET
EN_RDNEX:
LD   DE,4
ADD  IX,DE
INC  C
DJNZ EN_RDLOO
EN_RDNFO:
XOR  A
SCF
RET
ST_DTABL:
DW $21FD,$0000
DW $6097,$0000
DW $1950,$0000
DW $1C98,$0000
DW $1BF8,$0000
DW $15CC,$7080
DW $670C,$7080
DW $3B4C,$7080
DW $0829,$2DF0
;@ROUTINE OUT A CLOBBERS DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
ST_STAKE:
LD   HL,(ST_SPTR)
LD   A,(ST_SPART)
CALL TK_SREAD
LD   HL,(ST_SPTR)
INC  HL
LD   (ST_SPTR),HL
LD   HL,ST_SREM
DEC  (HL)
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
ST_NTKIN:
CALL TK_NEXT
LD   A,(TK_REC+TK_KOFF)
RET
;@ROUTINE OUT A,HL,IX,CARRY CLOBBERS BC,DE,IY,ZERO,SIGN,PARITY,HALFCARRY
ST_PEXPR:
LD   BC,(OU_CURSO)
JP   EX_PDEFR
;@ROUTINE OUT CARRY CLOBBERS A,HL,ZERO,SIGN,PARITY,HALFCARRY
ST_CPOSI:
LD   A,(TK_REC+TK_POFF)
LD   (ST_EPART),A
LD   HL,(TK_REC+TK_SOFF)
LD   (ST_EOFF),HL
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
ST_LFAIL:
LD   (ST_DETAI),A
LD   A,(TK_EPART)
LD   (ST_EPART),A
LD   HL,(TK_EOFF)
LD   (ST_EOFF),HL
LD   A,ST_SLEXI
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS C,HL,ZERO,SIGN,PARITY,HALFCARRY
ST_EHERE:
CALL ST_CPOSI
LD   A,(TK_REC+TK_KOFF)
CP   TK_DIR
JR   NZ,ST_ESAVE
;@ROUTINE OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_UDIR:
LD   A,TK_DIR
LD   C,ST_SDIR
JR   ST_FAIL
;@ROUTINE OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_ESAVE:
LD   A,(TK_REC+TK_KOFF)
LD   C,ST_SEXP
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_SFAIL:
LD   C,ST_SSYM
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_IFAIL:
LD   C,ST_SINS
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_OFAIL:
LD   C,ST_SOUT
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_EFAIL:
LD   C,ST_SEQUA
JR   ST_FAIL
ST_EUNRE:
LD   A,EX_UNRES
JR   ST_EFAIL
ST_EDELI:
LD   A,EX_SEPRI
JR   ST_EFAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_DFAIL:
LD   C,ST_SDIR
;@ROUTINE IN A,C OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
ST_FAIL:
LD   (ST_DETAI),A
LD   A,C
SCF
RET
ST_DUNR1:
LD   A,EX_UNRES
JR   ST_DFAIL
ST_DRANG:
LD   A,EX_SRANG
JR   ST_DFAIL
ST_DEXP:
LD   A,EX_SEPRI
JR   ST_DFAIL
ST_DDEL1:
LD   A,(TK_REC+TK_KOFF)
JR   ST_DFAIL
ST_DSTR1:
LD   A,TK_STRIN
JR   ST_DFAIL
ST_CEND:
ST_WBEG:
ST_WUNIO: DS 20
ST_KEY EQU ST_WUNIO
ST_INS EQU ST_WUNIO
ST_MNEM EQU ST_WUNIO+6
ST_MVALI EQU ST_WUNIO+7
ST_DIR EQU ST_WUNIO+8
ST_DVALI EQU ST_WUNIO+9
ST_DETAI EQU ST_WUNIO+10
ST_EVAL EQU ST_WUNIO+6
ST_ESIGN EQU ST_WUNIO+8
ST_DWIDT EQU ST_WUNIO
ST_DPKIN EQU ST_WUNIO+1
ST_DADDE EQU ST_WUNIO+2
ST_DFILL EQU ST_WUNIO+3
ST_DVAL EQU ST_WUNIO+4
ST_DPKI1 EQU ST_DVAL
ST_DCNT EQU ST_WUNIO+6
ST_DKEY EQU ST_WUNIO+8
ST_DSYM EQU ST_WUNIO+10
ST_DADR EQU ST_WUNIO+12
ST_SPTR EQU ST_WUNIO+14
ST_SREM EQU ST_WUNIO+16
ST_SCNT EQU ST_WUNIO+17
ST_SNIBB EQU ST_WUNIO+18
ST_SMODE EQU ST_WUNIO+19
ST_EPART: DB 0
ST_EOFF: DW 0
ST_SPART: DB 0
ST_WEND:
