;==============================================================================
;  Symbols, private scope and pending references
;==============================================================================
;
;  Store exact RADIX-40 symbol records in caller-owned memory. Globals grow
;  upward and remain for the build. Private symbols grow downward and are
;  discarded when the next global label begins a scope. A separate arena holds
;  unresolved references until the corresponding symbol is defined.
;
;  Principal entries:
;    SY_RESET  initialise symbol and pending arenas
;    SY_FIND   find an exact global or current-scope private name
;    SY_DECL   define a symbol without changing private scope
;    SY_DGLAB  define a global label and begin its private scope
;    SY_REF    find or create an undefined symbol record
;    SY_ADD    append one pending reference
;    SY_PEEK   inspect a matching pending reference without removing it
;    SY_TAKE   remove a matching pending reference after patch submission
;
;  Capacity checks occur before cursor publication. Scope changes are
;  transactional, so an undefined private label leaves the old scope intact.

SY_CBEG:
SY_RECB EQU 8
SY_RECB1 EQU 7
SY_KMASK EQU $07
SY_PMASK EQU 6
SY_DANCH EQU $80
SY_NAMEB EQU 6
SY_VALLO EQU 6
SY_VALHI EQU 7
SY_NHMAS EQU $07
SY_FSIGN EQU $20
SY_FDEFI EQU $40
SY_FPRIV EQU $80
SY_SOK EQU 0
SY_SNFOU EQU 1
SY_SDUPL EQU 2
SY_SSCAP EQU 3
SY_SPNSC EQU 4
SY_SUPRI EQU 5
SY_SPCAP EQU 6
SY_SPINV EQU 7
SY_SADEF EQU 8
SY_SPCA1 EQU 9
;@ROUTINE IN HL,DE OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
SY_RESET:
LD   (SY_ABASE),HL
LD   (SY_GEND),HL
LD   (SY_AEND),DE
LD   (SY_LBEG),DE
XOR  A
LD   (SY_SACTI),A
RET
;@ROUTINE IN HL,DE OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
SY_RESE1:
LD   (SY_ABAS1),HL
LD   (SY_NEXT),HL
LD   (SY_AEND1),DE
XOR  A
RET
;@ROUTINE IN B,HL,DE OUT A,DE,CARRY CLOBBERS BC,HL,IX,SIGN,PARITY,HALFCARRY,ZERO
EN_PSYM:
LD   A,B
OR   A
JR   Z,.PSINVALI
LD   A,(HL)
CP   $2E
JR   NZ,.PSGLBL
DEC  B
JR   Z,.PSINVALI
LD   A,B
CP   9
JR   NC,.PSINVALI
INC  HL
;@EXPECTOUT DE,CARRY
CALL EN_R40PK
JR   C,.PSINVALI
PUSH DE
DEC  DE
LD   A,(DE)
OR   SY_FPRIV
LD   (DE),A
POP  DE
XOR  A
RET
.PSGLBL:
;@EXPECTOUT DE,CARRY
CALL EN_R40PK
JR   C,.PSINVALI
XOR  A
RET
.PSINVALI:
XOR  A
INC  A
SCF
RET
;@ROUTINE IN HL OUT A,CARRY,IX CLOBBERS BC,HL,SIGN,PARITY,HALFCARRY,DE,ZERO
SY_FIND:
LD   (SY_OKEY),HL
PUSH HL
LD   DE,5
ADD  HL,DE
BIT  7,(HL)
POP  HL
JR   Z,.FINDGLBL
LD   A,(SY_SACTI)
OR   A
JR   Z,.PNSCOPE
LD   IX,(SY_LBEG)
LD   DE,(SY_AEND)
JR   .FINDLOOP
.FINDGLBL:
LD   IX,(SY_ABASE)
LD   DE,(SY_GEND)
.FINDLOOP:
CALL AT_CIDE
JR   Z,.NOTFOUND
PUSH DE
;@EXPECTOUT ZERO
CALL SY_KEQUA
POP  DE
JR   Z,.FOUND
LD   BC,SY_RECB
ADD  IX,BC
JR   .FINDLOOP
.FOUND:
XOR  A
RET
.NOTFOUND:
JP   SY_NFRET
.PNSCOPE:
JP   SY_GLPRI
;@ROUTINE IN IX OUT ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY,B,CARRY,A
SY_KEQUA:
PUSH IX
POP  DE
LD   HL,(SY_OKEY)
LD   B,5
.KELOOP:
LD   A,(DE)
CP   (HL)
RET  NZ
INC  DE
INC  HL
DJNZ .KELOOP
LD   A,(DE)
XOR  (HL)
AND  SY_NHMAS
RET
;@ROUTINE IN HL,DE OUT A,CARRY,IX CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
SY_DECL:
LD   (SY_OKEY),HL
LD   (SY_OVAL),DE
;@EXPECTOUT A,CARRY,IX
CALL SY_FIND
JR   C,.DMISSING
BIT  6,(IX+5)
JR   NZ,.DUPLICAT
LD   DE,(SY_OVAL)
LD   (IX+SY_VALLO),E
LD   (IX+SY_VALHI),D
LD   A,(IX+5)
OR   SY_FDEFI
LD   (IX+5),A
XOR  A
RET
.DUPLICAT:
JP   SY_GLDUP
.DMISSING:
CP   SY_SNFOU
JR   Z,.DINSERT
SCF
RET
.DINSERT:
LD   A,SY_FDEFI
;@EXPECTOUT A,CARRY,IX
JR   SY_INSER
;@ROUTINE IN HL OUT A,CARRY,IX,B CLOBBERS C,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
SY_REF:
LD   (SY_OKEY),HL
;@EXPECTOUT A,CARRY,IX
CALL SY_FIND
JR   C,.RMISSING
LD   B,0
RET
.RMISSING:
CP   SY_SNFOU
JR   Z,.RINSERT
SCF
RET
.RINSERT:
XOR  A
LD   (SY_OVAL),A
LD   (SY_OVAL+1),A
;@EXPECTOUT A,CARRY,IX
CALL SY_INSER
RET  C
LD   B,1
RET
;@ROUTINE IN A OUT A,CARRY,IX CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
SY_INSER:
LD   (SY_OFLAG),A
LD   HL,(SY_LBEG)
LD   DE,(SY_GEND)
LD   B,SY_RECB
CALL AT_RHCAP
JR   C,.NOCAP
.HASCAP:
LD   HL,(SY_OKEY)
LD   DE,5
ADD  HL,DE
BIT  7,(HL)
JR   NZ,.IPRIVATE
LD   IX,(SY_GEND)
PUSH IX
POP  HL
LD   DE,SY_RECB
ADD  HL,DE
LD   (SY_GEND),HL
JR   .CINSERT
.IPRIVATE:
LD   HL,(SY_LBEG)
LD   DE,SY_RECB
OR   A
SBC  HL,DE
LD   (SY_LBEG),HL
PUSH HL
POP  IX
.CINSERT:
LD   HL,(SY_OKEY)
PUSH IX
POP  DE
LD   BC,SY_NAMEB
LDIR
LD   A,(SY_OFLAG)
OR   (IX+5)
LD   (IX+5),A
LD   DE,(SY_OVAL)
LD   (IX+SY_VALLO),E
LD   (IX+SY_VALHI),D
XOR  A
RET
.NOCAP:
LD   A,SY_SSCAP
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
SY_ASCOP:
CALL SY_VSCOP
RET  C
SY_CSCOP:
LD   HL,(SY_AEND)
LD   (SY_LBEG),HL
LD   A,1
LD   (SY_SACTI),A
XOR  A
RET
;@ROUTINE IN HL,DE OUT A,CARRY,IX CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
SY_DGLAB:
LD   (SY_OKEY),HL
LD   (SY_OVAL),DE
LD   DE,5
ADD  HL,DE
BIT  7,(HL)
JR   NZ,SY_GLPRI
LD   HL,(SY_OKEY)
CALL SY_FIND
JR   C,SY_GLMIS
BIT  6,(IX+5)
JR   NZ,SY_GLDUP
XOR  A
LD   (SY_OFLAG),A
JR   SY_GLVAL
SY_GLMIS:
CP   SY_SNFOU
RET  NZ
LD   A,1
LD   (SY_OFLAG),A
SY_GLVAL:
CALL SY_VSCOP
RET  C
LD   A,(SY_OFLAG)
OR   A
JR   Z,SY_GLCMT
LD   HL,(SY_AEND)
LD   DE,(SY_GEND)
LD   B,SY_RECB
CALL AT_RHCAP
JR   C,SY_GLCAP
SY_GLCMT:
LD   HL,(SY_AEND)
LD   (SY_LBEG),HL
LD   A,1
LD   (SY_SACTI),A
LD   HL,(SY_OKEY)
LD   DE,(SY_OVAL)
CALL SY_DECL
RET  NC
LD   A,SY_SPINV
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS HALFCARRY
SY_GLPRI:
LD   A,SY_SPNSC
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS HALFCARRY
SY_GLDUP:
LD   A,SY_SDUPL
SCF
RET
SY_GLCAP:
LD   A,SY_SSCAP
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS IX,DE,BC,ZERO,SIGN,PARITY,HALFCARRY,HL
SY_VSCOP:
LD   IX,(SY_LBEG)
LD   DE,(SY_AEND)
SY_VSLOO:
CALL AT_CIDE
JR   Z,SY_VPEND
BIT  6,(IX+5)
JR   Z,SY_VUNDE
LD   BC,SY_RECB
ADD  IX,BC
JR   SY_VSLOO
SY_VPEND:
LD   IX,(SY_ABAS1)
LD   DE,(SY_NEXT)
SY_VPLOO:
CALL AT_CIDE
JR   Z,SY_VOK
LD   L,(IX+0)
LD   H,(IX+1)
PUSH DE
LD   DE,5
ADD  HL,DE
BIT  7,(HL)
POP  DE
JR   NZ,SY_VINVA
LD   BC,SY_RECB1
ADD  IX,BC
JR   SY_VPLOO
SY_VOK:
XOR  A
RET
SY_VUNDE:
LD   A,SY_SUPRI
SCF
RET
SY_VINVA:
LD   A,SY_SPINV
SCF
RET
;@ROUTINE IN A,IX,DE,BC OUT A,CARRY CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY,ZERO
SY_ADD:
BIT  6,(IX+5)
JR   NZ,.ADEFINED
PUSH AF
PUSH BC
PUSH DE
LD   HL,(SY_AEND1)
LD   DE,(SY_NEXT)
LD   B,SY_RECB1
CALL AT_RHCAP
JR   C,.NCSTACK
.HASCAP:
LD   HL,(SY_NEXT)
PUSH IX
POP  DE
LD   (HL),E
INC  HL
LD   (HL),D
INC  HL
POP  DE
LD   (HL),E
INC  HL
LD   (HL),D
INC  HL
POP  BC
LD   (HL),B
INC  HL
LD   (HL),C
INC  HL
POP  AF
LD   (HL),A
INC  HL
LD   (SY_NEXT),HL
XOR  A
RET
.NCSTACK:
POP  DE
POP  BC
POP  AF
.NOCAP:
LD   A,SY_SPCAP
SCF
RET
.ADEFINED:
LD   A,SY_SADEF
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
SY_CCAP:
LD   HL,(SY_AEND1)
LD   DE,(SY_NEXT)
PUSH BC
LD   B,SY_RECB1
CALL AT_RHCAP
POP  BC
JR   C,SY_CNCAP
XOR  A
RET
SY_CNCAP:
LD   A,SY_SPCAP
SCF
RET
;@ROUTINE IN IX OUT A,CARRY,BC,DE,IX CLOBBERS SIGN,PARITY,HALFCARRY,ZERO,HL
SY_PEEK:
SY_FIND1:
PUSH IX
POP  HL
LD   (SY_OSYM),HL
LD   IX,(SY_ABAS1)
LD   DE,(SY_NEXT)
.PEEKLOOP:
CALL AT_CIDE
JR   Z,SY_NFRET
LD   L,(IX+0)
LD   H,(IX+1)
PUSH DE
LD   DE,(SY_OSYM)
OR   A
SBC  HL,DE
POP  DE
JR   Z,.PFOUND
LD   BC,SY_RECB1
ADD  IX,BC
JR   .PEEKLOOP
.PFOUND:
LD   E,(IX+2)
LD   D,(IX+3)
LD   B,(IX+4)
LD   C,(IX+5)
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HALFCARRY
SY_NFRET:
LD   A,SY_SNFOU
SCF
RET
;@ROUTINE IN IX OUT A,CARRY MAYBE-OUT BC,DE CLOBBERS HL,IX,SIGN,PARITY,HALFCARRY,BC,DE,ZERO
SY_TAKE:
CALL SY_FIND1
RET  C
PUSH BC
PUSH DE
LD   HL,(SY_NEXT)
LD   DE,SY_RECB1
OR   A
SBC  HL,DE
LD   (SY_NEXT),HL
PUSH IX
POP  DE
OR   A
SBC  HL,DE
JR   Z,.TRETURN
LD   HL,(SY_NEXT)
PUSH IX
POP  DE
LD   BC,SY_RECB1
LDIR
.TRETURN:
POP  DE
POP  BC
XOR  A
RET
;@ROUTINE IN IX,DE OUT HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY CLOBBERS A
AT_CIDE:
PUSH IX
POP  HL
OR   A
SBC  HL,DE
RET
;@ROUTINE IN HL,DE,B OUT CARRY MAYBE-OUT ZERO CLOBBERS A,HL,SIGN,PARITY,HALFCARRY
AT_RHCAP:
OR   A
SBC  HL,DE
RET  C
LD   A,H
OR   A
RET  NZ
LD   A,L
CP   B
RET
SY_CEND:
SY_WBEG:
SY_ABASE: DW 0
SY_AEND: DW 0
SY_GEND: DW 0
SY_LBEG: DW 0
SY_SACTI: DB 0
SY_OKEY: DW 0
SY_OVAL: DW 0
SY_OFLAG: DB 0
SY_ABAS1: DW 0
SY_AEND1: DW 0
SY_NEXT: DW 0
SY_OSYM EQU SY_OKEY
SY_WEND:
