;==============================================================================
;  Streaming tokenizer
;==============================================================================
;
;  Read one prepared source part through the source-byte service and publish
;  names, numbers, strings, punctuation, line endings and end of part. Lexeme
;  bytes remain in a fixed buffer only until the next tokenizer call.
;
;  Principal entries:
;    TK_RESET  select a source part and reset its logical position
;    TK_SPEEK  inspect the next source byte without consuming it
;    TK_STAKE  consume one byte into the current token buffer
;    TK_NEXT   publish the next token record
;
;  TK_SREAD is the platform source seam. The checked core contains the bounded
;  memory implementation below. Native platform builders replace only the
;  explicitly marked body with a jump to their source provider.

TK_CBEG:
TK_EOF EQU 0
TK_EOL EQU 1
TK_NAME EQU 2
TK_DIR EQU 3
TK_NUMBE EQU 4
TK_STRIN EQU 5
TK_COMMA EQU 6
TK_COLON EQU 7
TK_LPARE EQU 8
TK_RPARE EQU 9
TK_PLUS EQU 10
TK_MINUS EQU 11
TK_STAR EQU 12
TK_SLASH EQU 13
TK_PERCE EQU 14
TK_AMPER EQU 15
TK_CARET EQU 16
TK_PIPE EQU 17
TK_TILDE EQU 18
TK_APOST EQU 19
TK_LSHIF EQU 20
TK_RSHIF EQU 21
TK_CUR EQU 22
TK_SIB EQU 1
TK_SNTLO EQU 2
TK_SINUM EQU 3
TK_SNOVE EQU 4
TK_SUSTR EQU 5
TK_SIESC EQU 6
TK_SSTLO EQU 7
TK_SBSRA EQU 8
TK_SUDIR EQU 9
TK_SUCHA EQU 10
TK_SICHA EQU 11
TK_KOFF EQU 0
TK_POFF EQU 1
TK_SOFF EQU 2
TK_LOFF EQU 4
TK_LOFF1 EQU 6
TK_VOFF EQU 7
TK_RECB EQU 9
;@ROUTINE IN A,HL,DE OUT A,IX,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
TK_RESET:
PUSH AF
PUSH HL
PUSH DE
EX   DE,HL
OR   A
SBC  HL,DE
JR   C,.RBSRANGE
LD   (TK_SEND),HL
POP  DE
POP  HL
POP  AF
LD   (TK_SPART),A
LD   (TK_SRCBA),HL
XOR  A
LD   (TK_SCURS),A
LD   (TK_SCURS+1),A
LD   (TK_SOSTA),A
LD   (TK_SOSTA+1),A
LD   (TK_LHTOK),A
LD   (TK_EPEND),A
LD   (TK_ESTAT),A
LD   (TK_REC+TK_KOFF),A
LD   IX,TK_REC
RET
.RBSRANGE:
POP  DE
POP  HL
POP  AF
.BSRANGE:
LD   A,TK_SBSRA
SCF
RET
;@ROUTINE OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
TK_SPEEK:
LD   HL,(TK_SCURS)
LD   DE,(TK_SEND)
OR   A
SBC  HL,DE
JR   Z,.SPEOF
ADD  HL,DE
.SRCPEEKB:
LD   A,(TK_SPART)
CALL TK_SREAD
OR   A
RET
.SPEOF:
SCF
RET
;@@ATOM_SOURCE_READ_BEGIN@@
;@ROUTINE IN A,HL OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
TK_SREAD:
LD   DE,(TK_SRCBA)
ADD  HL,DE
LD   A,(HL)
OR   A
RET
;@@ATOM_SOURCE_READ_END@@
;@ROUTINE OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
TK_STAKE:
PUSH BC
CALL TK_SPEEK
JR   C,.STEOF
LD   D,A
LD   HL,(TK_SCURS)
INC  HL
LD   (TK_SCURS),HL
LD   HL,(TK_SOSTA)
INC  HL
LD   (TK_SOSTA),HL
LD   A,(TK_BCNT)
LD   C,A
LD   B,0
LD   HL,TK_TBUF
ADD  HL,BC
LD   A,D
LD   (HL),A
LD   (TK_PREV),A
LD   A,(TK_BCNT)
INC  A
LD   (TK_BCNT),A
LD   A,D
POP  BC
OR   A
RET
.STEOF:
POP  BC
SCF
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,HL,SIGN,PARITY,HALFCARRY
TK_BEG:
LD   HL,TK_TBUF
LD   (TK_SPTR),HL
LD   HL,(TK_SOSTA)
LD   (TK_SOFF1),HL
XOR  A
LD   (TK_BCNT),A
LD   (TK_SLEN),A
LD   (TK_SVAL),A
LD   (TK_SVAL+1),A
RET
;@ROUTINE IN A OUT A,IX,CARRY CLOBBERS HL,SIGN,PARITY,HALFCARRY,ZERO
TK_CMT:
LD   (TK_REC+TK_KOFF),A
LD   A,(TK_SPART)
LD   (TK_REC+TK_POFF),A
LD   HL,(TK_SOFF1)
LD   (TK_REC+TK_SOFF),HL
LD   HL,(TK_SPTR)
LD   (TK_REC+TK_LOFF),HL
LD   A,(TK_SLEN)
LD   (TK_REC+TK_LOFF1),A
LD   HL,(TK_SVAL)
LD   (TK_REC+TK_VOFF),HL
LD   IX,TK_REC
LD   A,(TK_REC+TK_KOFF)
OR   A
RET
;@ROUTINE IN A OUT A,IX,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
TK_FIN:
PUSH AF
LD   A,1
LD   (TK_LHTOK),A
POP  AF
JR   TK_CMT
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,SIGN,PARITY,ZERO
TK_FAIL:
LD   (TK_ESTAT),A
LD   HL,(TK_SOFF1)
LD   (TK_SCURS),HL
LD   (TK_SOSTA),HL
LD   A,(TK_SPART)
LD   (TK_EPART),A
LD   HL,(TK_SOFF1)
LD   (TK_EOFF),HL
LD   A,(TK_ESTAT)
SCF
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
TK_ILETT:
PUSH BC
LD   C,A
OR   $20
SUB  $61
CP   26
LD   A,C
POP  BC
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
TK_INBEG:
CALL TK_ILETT
RET  C
CP   $5F
JR   Z,TK_CYES
OR   A
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
TK_INB:
CALL TK_INBEG
RET  C
CP   $30
JR   C,TK_CNO
CP   $39+1
RET  C
TK_CNO:
OR   A
RET
TK_CYES:
SCF
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
TK_HDIGI:
CP   $30
JR   C,.HEXNO
CP   $39+1
JR   C,.HDECIMAL
OR   $20
SUB  $61
CP   6
JR   NC,.HEXNO
ADD  A,10
SCF
RET
.HDECIMAL:
SUB  $30
SCF
RET
.HEXNO:
OR   A
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_SNAME:
LD   C,8
CALL TK_SPEEK
CP   $2E
JR   NZ,.SNGLBL
LD   C,9
CALL TK_STAKE
CALL TK_SPEEK
JP   C,TK_IB
CALL TK_INBEG
JP   NC,TK_IB
LD   B,1
JR   .SNLOOP
.SNGLBL:
LD   B,0
.SNLOOP:
CALL TK_SPEEK
JR   C,.SNDONE
CALL TK_INB
JR   NC,.SNDONE
INC  B
LD   A,C
CP   B
JR   C,TK_NTLON
CALL TK_STAKE
JR   .SNLOOP
.SNDONE:
LD   A,B
LD   (TK_SLEN),A
LD   A,TK_NAME
JP   TK_FIN
TK_NTLON:
LD   A,TK_SNTLO
JP   TK_FAIL
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_SDLED:
LD   B,0
.SDLLOOK:
CALL TK_SPEEK
JR   C,.SDLSELEC
CALL TK_INB
JR   NC,.SDLSELEC
CALL TK_STAKE
INC  B
JP   Z,TK_INUMB
JR   .SDLLOOK
.SDLSELEC:
LD   A,B
LD   (TK_SLEN),A
PUSH BC
LD   HL,TK_TBUF
LD   C,B
LD   B,0
ADD  HL,BC
DEC  HL
LD   A,(HL)
POP  BC
AND  $DF
LD   C,0
CP   $48
JR   Z,.SDLHEX
CP   $42
JR   NZ,.SDLPREPA
INC  C
JR   .SDLSUFFI
.SDLHEX:
LD   C,4
.SDLSUFFI:
DEC  B
.SDLPREPA:
LD   A,B
OR   A
JP   Z,TK_INUMB
LD   (TK_DSEEN),A
LD   IX,(TK_SPTR)
LD   HL,0
LD   A,C
OR   A
JR   Z,.SDLDECIM
CP   1
JR   Z,.SDLBINAR
.SDLHLOOP:
LD   A,(IX+0)
CALL TK_HDIGI
JP   NC,TK_INUMB
LD   E,A
LD   A,H
AND  $F0
JP   NZ,TK_NOVER
ADD  HL,HL
ADD  HL,HL
ADD  HL,HL
ADD  HL,HL
LD   A,L
OR   E
LD   L,A
INC  IX
LD   A,(TK_DSEEN)
DEC  A
LD   (TK_DSEEN),A
JR   NZ,.SDLHLOOP
JR   .SDLFIN
.SDLBINAR:
LD   A,(IX+0)
SUB  $30
JP   C,TK_INUMB
CP   2
JP   NC,TK_INUMB
LD   E,A
ADD  HL,HL
JP   C,TK_NOVER
LD   A,L
OR   E
LD   L,A
INC  IX
LD   A,(TK_DSEEN)
DEC  A
LD   (TK_DSEEN),A
JR   NZ,.SDLBINAR
JR   .SDLFIN
.SDLDECIM:
LD   A,(IX+0)
SUB  $30
JP   C,TK_INUMB
CP   10
JP   NC,TK_INUMB
LD   C,A
LD   A,H
CP   $19
JR   C,.SDLDACCU
JP   NZ,TK_NOVER
LD   A,L
CP   $99
JR   C,.SDLDACCU
JP   NZ,TK_NOVER
LD   A,C
CP   6
JP   NC,TK_NOVER
.SDLDACCU:
LD   D,0
LD   E,C
ADD  HL,HL
LD   B,H
LD   C,L
ADD  HL,HL
ADD  HL,HL
ADD  HL,BC
ADD  HL,DE
INC  IX
LD   A,(TK_DSEEN)
DEC  A
LD   (TK_DSEEN),A
JR   NZ,.SDLDECIM
.SDLFIN:
LD   (TK_SVAL),HL
TK_FNUMB:
LD   A,TK_NUMBE
JP   TK_FIN
;@ROUTINE IN BC OUT A,IX,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_SBASE:
LD   HL,0
XOR  A
LD   (TK_DSEEN),A
.SBLOOP:
PUSH HL
CALL TK_SPEEK
POP  HL
JR   C,.SBEOF
LD   D,A
BIT  2,C
JR   Z,.SBDIGIT
CALL TK_HDIGI
JR   NC,.SBDONE
JR   .SBDIGIT1
.SBDIGIT:
SUB  $30
JR   C,.SBDONE
CP   2
JR   NC,.SBDONE
.SBDIGIT1:
LD   E,A
BIT  2,C
JR   Z,.SBSHIFT
LD   A,H
AND  $F0
JR   NZ,TK_NOVER
ADD  HL,HL
ADD  HL,HL
ADD  HL,HL
ADD  HL,HL
JR   .SBMERGE
.SBSHIFT:
ADD  HL,HL
JR   C,TK_NOVER
.SBMERGE:
LD   A,L
OR   E
LD   L,A
PUSH HL
CALL TK_STAKE
POP  HL
INC  B
JR   Z,TK_INUMB
LD   A,1
LD   (TK_DSEEN),A
JR   .SBLOOP
.SBDONE:
LD   A,(TK_DSEEN)
OR   A
JR   Z,TK_INUMB
LD   A,D
CALL TK_INB
JR   C,TK_INUMB
JR   .SBFIN
.SBEOF:
LD   A,(TK_DSEEN)
OR   A
JR   Z,TK_INUMB
.SBFIN:
LD   (TK_SVAL),HL
TK_FNLEN:
LD   A,B
LD   (TK_SLEN),A
JR   TK_FNUMB
TK_INUMB:
LD   A,TK_SINUM
JP   TK_FAIL
TK_NOVER:
LD   A,TK_SNOVE
JP   TK_FAIL
;@ROUTINE OUT A,IX,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC
TK_SSTRI:
LD   B,0
CALL TK_STAK1
JP   C,TK_FAIL
.SSLOOP:
CALL TK_STAK1
JP   C,TK_FAIL
CALL TK_ILEND
JR   Z,TK_USTRI
CP   $20
JR   C,TK_IB
CP   $7F
JR   NC,TK_IB
CP   $22
JR   Z,.SSDONE
CP   $5C
JR   NZ,.SSLOOP
CALL TK_STAK1
JP   C,TK_FAIL
CP   $78
JR   Z,.SHESCAPE
CALL TK_DESCA
JR   C,TK_IESCA
JR   .SSLOOP
.SHESCAPE:
CALL TK_STAK1
JP   C,TK_FAIL
CALL TK_HDIGI
JR   NC,TK_IESCA
CALL TK_STAK1
JP   C,TK_FAIL
CALL TK_HDIGI
JR   NC,TK_IESCA
JR   .SSLOOP
.SSDONE:
LD   A,B
LD   (TK_SLEN),A
LD   A,TK_STRIN
JP   TK_FIN
;@ROUTINE IN B OUT A,B,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_STAK1:
CALL TK_STAKE
JR   C,.STEOF
INC  B
RET  NZ
LD   A,TK_SSTLO
SCF
RET
.STEOF:
LD   A,TK_SUSTR
SCF
RET
TK_IESCA:
LD   A,TK_SIESC
JP   TK_FAIL
TK_USTRI:
LD   A,TK_SUSTR
JP   TK_FAIL
TK_UCHAR:
LD   A,TK_SUCHA
JP   TK_FAIL
TK_ICHAR:
LD   A,TK_SICHA
JP   TK_FAIL
TK_IB:
LD   A,TK_SIB
JP   TK_FAIL
;@ROUTINE OUT CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY,A
TK_SCOMM:
.SCLOOP:
CALL TK_SPEEK
RET  C
CALL TK_ILEND
RET  Z
CALL TK_STAKE
JR   .SCLOOP
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IY
TK_NEXT:
.NEXTLOOP:
CALL TK_BEG
CALL TK_SPEEK
JP   C,.ATEOF
CP   $20
JR   Z,.SKIPB
CP   $09
JR   Z,.SKIPB
CP   $0A
JP   Z,.LF
CP   $0D
JP   Z,.CRLF
CP   $3B
JR   Z,.COMMENT
CP   $2E
JP   Z,TK_SNAME
CP   $22
JP   Z,TK_SSTRI
CP   $27
JP   Z,.APOSTROP
CP   $24
JR   Z,.DOLLAR
CP   $25
JR   Z,.PERCENT
CP   $3C
JP   Z,.LSHIFT
CP   $3E
JP   Z,.RSHIFT
CP   $30
JR   C,.TRYNAME
CP   $39+1
JP   C,TK_SDLED
.TRYNAME:
CALL TK_INBEG
JP   C,TK_SNAME
LD   HL,TK_PTABL
LD   B,TK_PCNT
.PLOOP:
CP   (HL)
INC  HL
JR   Z,.PUNCTUAT
INC  HL
DJNZ .PLOOP
JR   TK_IB
.PUNCTUAT:
LD   C,(HL)
CALL TK_STAKE
LD   A,1
JR   .FPUNCTUA
.SKIPB:
CALL TK_STAKE
JR   .NEXTLOOP
.COMMENT:
CALL TK_SCOMM
JR   .NEXTLOOP
.DOLLAR:
CALL TK_STAKE
CALL TK_SPEEK
JR   C,.CLOCATIO
LD   B,A
CALL TK_HDIGI
JR   C,.DNUMBER
LD   A,B
CALL TK_INB
JP   C,TK_INUMB
.CLOCATIO:
LD   A,1
LD   (TK_SLEN),A
LD   A,TK_CUR
JP   TK_FIN
.DNUMBER:
LD   B,1
LD   C,4
JP   TK_SBASE
.PERCENT:
CALL TK_STAKE
CALL TK_SPEEK
JR   C,.PTOK
CP   $30
JR   Z,.PNUMBER
CP   $31
JR   Z,.PNUMBER
CALL TK_ILETT
JR   NC,.PTOK
LD   A,(TK_LHTOK)
OR   A
JR   NZ,.PTOK
LD   A,TK_SUDIR
JP   TK_FAIL
.PTOK:
LD   A,1
LD   (TK_SLEN),A
LD   A,TK_PERCE
JP   TK_FIN
.PNUMBER:
LD   B,1
LD   C,1
JP   TK_SBASE
.LSHIFT:
LD   C,TK_LSHIF
JR   .SHIFT
.RSHIFT:
LD   C,TK_RSHIF
.SHIFT:
LD   B,A
CALL TK_STAKE
CALL TK_SPEEK
JP   C,TK_IB
CP   B
JP   NZ,TK_IB
CALL TK_STAKE
LD   A,2
.FPUNCTUA:
LD   (TK_SLEN),A
LD   A,C
JP   TK_FIN
.LF:
CALL TK_STAKE
LD   A,1
LD   (TK_SLEN),A
JR   .FINLINE
.CRLF:
CALL TK_STAKE
CALL TK_SPEEK
JP   C,TK_IB
CP   $0A
JP   NZ,TK_IB
CALL TK_STAKE
LD   A,2
LD   (TK_SLEN),A
.FINLINE:
XOR  A
LD   (TK_EPEND),A
LD   A,(TK_LHTOK)
OR   A
JP   Z,.NEXTLOOP
XOR  A
LD   (TK_LHTOK),A
LD   A,TK_EOL
JP   TK_CMT
.ATEOF:
LD   A,(TK_EPEND)
OR   A
JR   NZ,.EMITEOF
LD   A,(TK_LHTOK)
OR   A
JR   Z,.EMITEOF
XOR  A
LD   (TK_LHTOK),A
INC  A
LD   (TK_EPEND),A
XOR  A
LD   (TK_SLEN),A
LD   A,TK_EOL
JP   TK_CMT
.EMITEOF:
XOR  A
LD   (TK_SLEN),A
JP   TK_CMT
.APOSTROP:
LD   HL,(TK_SOFF1)
LD   A,H
OR   L
JR   Z,TK_SCHAR
LD   A,(TK_PREV)
CALL TK_INB
JR   NC,TK_SCHAR
CALL TK_STAKE
LD   A,1
LD   (TK_SLEN),A
LD   A,TK_APOST
JP   TK_FIN
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
TK_SCHAR:
LD   B,1
CALL TK_STAKE
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_ILEND
JP   Z,TK_UCHAR
CP   $27
JP   Z,TK_ICHAR
CP   $5C
JR   Z,.SCESCAPE
CP   $20
JP   C,TK_IB
CP   $7F
JP   NC,TK_IB
LD   (TK_SVAL),A
JR   .SCCLOSE
.SCESCAPE:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CP   $78
JR   Z,.SCHEX
CALL TK_DESCA
JP   C,TK_IESCA
LD   (TK_SVAL),A
JR   .SCCLOSE
.SCHEX:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_HDIGI
JP   NC,TK_IESCA
ADD  A,A
ADD  A,A
ADD  A,A
ADD  A,A
LD   (TK_SVAL),A
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_HDIGI
JP   NC,TK_IESCA
LD   HL,TK_SVAL
OR   (HL)
LD   (TK_SVAL),A
.SCCLOSE:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_ILEND
JP   Z,TK_UCHAR
CP   $27
JP   NZ,TK_ICHAR
JP   TK_FNLEN
TK_RCEND:
;@ROUTINE OUT A,B,HL
TK_LLEXE:
LD   HL,(TK_REC+TK_LOFF)
LD   A,(TK_REC+TK_LOFF1)
LD   B,A
RET
TK_IBEG:
TK_PTABL:
DB $2C,TK_COMMA
DB $3A,TK_COLON
DB $28,TK_LPARE
DB $29,TK_RPARE
DB $2B,TK_PLUS
DB $2D,TK_MINUS
DB $2A,TK_STAR
DB $2F,TK_SLASH
DB $26,TK_AMPER
DB $5E,TK_CARET
DB $7C,TK_PIPE
DB $7E,TK_TILDE
DB $27,TK_APOST
TK_PEND:
TK_PCNT EQU (TK_PEND-TK_PTABL)/2
TK_ETABL:
DB $30,0,$6E,$0A,$72,$0D,$74,$09,$27,$27,$22,$22,$5C,$5C
TK_ECNT EQU 7
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_DESCA:
LD   HL,TK_ETABL
LD   C,TK_ECNT
.DELOOP:
CP   (HL)
JR   Z,.DEFOUND
INC  HL
INC  HL
DEC  C
JR   NZ,.DELOOP
SCF
RET
.DEFOUND:
INC  HL
LD   A,(HL)
RET
;@ROUTINE IN A OUT A,ZERO CLOBBERS CARRY,SIGN,PARITY,HALFCARRY
TK_ILEND:
CP   $0A
RET  Z
CP   $0D
RET
TK_IEND:
TK_CEND:
TK_WBEG:
TK_SRCBA: DW 0
TK_SCURS: DW 0
TK_SEND: DW 0
TK_SOSTA: DW 0
TK_SPART: DB 0
TK_LHTOK: DB 0
TK_EPEND: DB 0
TK_SPTR: DW 0
TK_BCNT: DB 0
TK_PREV: DB 0
TK_SOFF1: DW 0
TK_SLEN: DB 0
TK_SVAL: DW 0
TK_DSEEN: DB 0
TK_ESTAT EQU TK_SLEN
TK_EPART EQU TK_SVAL
TK_EOFF EQU TK_SVAL+1
TK_REC: DS TK_RECB
TK_TBUF: DS 256
TK_WEND:
