; ATOM NATIVE SOURCE ENTRY POINT.
%INCLUDE "encoder.asm"
%INCLUDE "symbols.asm"
%INCLUDE "tokenizer.asm"
%INCLUDE "expression.asm"
%INCLUDE "expression-arithmetic.asm"
%INCLUDE "patch.asm"
%INCLUDE "parser.asm"
%INCLUDE "output.asm"
%INCLUDE "statements.asm"
%INCLUDE "driver.asm"
%INCLUDE "host-services.asm"
